### PR TITLE
Log cleanup

### PR DESCRIPTION
**Pull request by martinpitt**
Log everything from the controller into a single kstest.log file with a consistent format. Due to using both our own logger and the pylorax logging in parallel, the output was split between kstest-logger.log, livemedia.log, and program.log; the first and third were lacking timestamps, the first and second had a large overlap of logging the same messages, and as a human it is hard to correctly interleave the messages in your mind.

The other commits clean up some individual log messages, and drop the obsolete scripts/kstest-runner. @rvykydal , @M4rtinK, do we use that script anywhere else? If so, I'll revert the dropping and instead port it to the new logging structure, but ATM I'm not even sure in which environment to call it.

[Run with these commits](https://github.com/rhinstaller/kickstart-tests/actions/runs/391535926)

### CODE REVIEW

**Comment by martinpitt** [comment]
Example console output from logging a working (container) and failing (basic-ftp) test:
```
Running tests: container.sh basic-ftp.sh 
INFO:apply-ksappend.py: running ksappend substitution on: container.ks.in
INFO:apply-ksappend.py: running ksappend substitution on: basic-ftp.ks.in
================================================================
INFO: install_log = /var/tmp/kstest-basic-ftp.ct12lnvh/virt-install.log
INFO: virt-install ['-n', 'kstest-basic-ftp_(14b413a6-6877-41cf-abb7-bd6d4f467b11)', '-r', '2048', '--noautoconsole', '--vcpus', '1', '--rng', '/dev/random', '--noreboot', '--graphics', 'vnc,listen=0.0.0.0', '--initrd-inject', '/opt/kstest/kickstart-tests/basic-ftp.ks', '--disk', 'path=/var/tmp/kstest-basic-ftp.ct12lnvh/disk-a.img,cache=unsafe,bus=sata', '--disk', 'path=/var/tmp/kstest-basic-ftp.ct12lnvh/boot.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'inst.ks=file:/basic-ftp.ks debug=1 inst.debug rd.shell=0 rd.emergency=poweroff inst.kernel.hung_task_timeout_secs=1200 inst.stage2=hd:CDLABEL=Fedora-S-dvd-x86_64-rawh', '--location', '/var/tmp/kstest-basic-ftp.ct12lnvh/boot.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img', '--channel', 'tcp,host=127.0.0.1:48889,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']
...........
INFO: Installation error detected. See logfile.
ERROR: Install failed: Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
ERROR: ERROR: Image creation failed: Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
INFO: RESULT:basic-ftp:6f1f6c43963d:FAILED:Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
================================================================
INFO: install_log = /var/tmp/kstest-container.nyqdprth/virt-install.log
INFO: virt-install ['-n', 'kstest-container_(c28ec95b-4e2a-4373-8fb6-c21374e557bb)', '-r', '2048', '--noautoconsole', '--vcpus', '1', '--rng', '/dev/random', '--noreboot', '--graphics', 'vnc,listen=0.0.0.0', '--initrd-inject', '/opt/kstest/kickstart-tests/container.ks', '--disk', 'path=/var/tmp/kstest-container.nyqdprth/disk-a.img,cache=unsafe,bus=sata', '--disk', 'path=/var/tmp/kstest-container.nyqdprth/boot.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'inst.ks=file:/container.ks debug=1 inst.debug rd.shell=0 rd.emergency=poweroff inst.kernel.hung_task_timeout_secs=1200 inst.stage2=hd:CDLABEL=Fedora-S-dvd-x86_64-rawh', '--location', '/var/tmp/kstest-container.nyqdprth/boot.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img', '--channel', 'tcp,host=127.0.0.1:51727,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']
..............................................................
INFO: Install finished. Or at least virt shut down.
INFO: Disk Image install successful
INFO: SUMMARY
-------
Logs are in /var/tmp/kstest-container.nyqdprth
Disk image(s) at /var/tmp/kstest-container.nyqdprth/disk-a.img,cache=unsafe
Results are in /var/tmp/kstest-container.nyqdprth

INFO: RESULT:container:6f1f6c43963d:SUCCESS:test done
[...]
TEST                                                    | HOST            | RESULT     | EXPLANATION
--------------------------------------------------------+-----------------+------------+-------------------------------------------
FAILED                                                  | Test failed on line | FAILED     | error in log: //ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it::
SUCCESS                                                 | test done       |            | 
```

The verbose kstest.log now looks like this:
```
2020-11-30 08:31:43,384 DEBUG: Preparing test
2020-11-30 08:31:43,384 DEBUG: Copying image to temp directory /var/tmp/kstest-basic-ftp.ct12lnvh
2020-11-30 08:31:43,978 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'prepare']
2020-11-30 08:31:43,996 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'kernel_args']
2020-11-30 08:31:44,004 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'prepare_disks']
2020-11-30 08:31:44,141 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'prepare_network']
2020-11-30 08:31:44,152 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'boot_args']
2020-11-30 08:31:44,160 DEBUG: Running command: ['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-basic-ftp.ct12lnvh', '-t', '/opt/kstest/kickstart-tests/basic-ftp.sh', 'inject_ks_to_initrd']
2020-11-30 08:31:44,169 DEBUG: Virtual Configuration: disk_paths: ['/var/tmp/kstest-basic-ftp.ct12lnvh/disk-a.img,cache=unsafe'], install_logpath: /var/tmp/kstest-basic-ftp.ct12lnvh/virt-install.log, iso_path: /var/tmp/kstest-basic-ftp.ct12lnvh/boot.iso, keep_image: True, kernel_args: debug=1 inst.debug rd.shell=0 rd.emergency=poweroff inst.kernel.hung_task_timeout_secs=1200, ks_paths: ['/opt/kstest/kickstart-tests/basic-ftp.ks'], log_path: /var/tmp/kstest-basic-ftp.ct12lnvh/kstest.log, ram: 2048, temp_dir: /var/tmp/kstest-basic-ftp.ct12lnvh, test_name: basic-ftp, timeout: 60, vcpu_count: 1, vnc: vnc,listen=0.0.0.0
2020-11-30 08:31:44,170 INFO: install_log = /var/tmp/kstest-basic-ftp.ct12lnvh/virt-install.log
2020-11-30 08:31:44,171 DEBUG: Starting virtual machine
2020-11-30 08:31:44,175 INFO: virt-install ['-n', 'kstest-basic-ftp_(14b413a6-6877-41cf-abb7-bd6d4f467b11)', '-r', '2048', '--noautoconsole', '--vcpus', '1', '--rng', '/dev/random', '--noreboot', '--graphics', 'vnc,listen=0.0.0.0', '--initrd-inject', '/opt/kstest/kickstart-tests/basic-ftp.ks', '--disk', 'path=/var/tmp/kstest-basic-ftp.ct12lnvh/disk-a.img,cache=unsafe,bus=sata', '--disk', 'path=/var/tmp/kstest-basic-ftp.ct12lnvh/boot.iso,device=cdrom,readonly=on,shareable=on', '--extra-args', 'inst.ks=file:/basic-ftp.ks debug=1 inst.debug rd.shell=0 rd.emergency=poweroff inst.kernel.hung_task_timeout_secs=1200 inst.stage2=hd:CDLABEL=Fedora-S-dvd-x86_64-rawh', '--location', '/var/tmp/kstest-basic-ftp.ct12lnvh/boot.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img', '--channel', 'tcp,host=127.0.0.1:48889,mode=connect,target_type=virtio,name=org.fedoraproject.anaconda.log.0']
2020-11-30 08:33:43,291 INFO: Installation error detected. See logfile.
2020-11-30 08:33:43,291 DEBUG: shutting down kstest-basic-ftp_(14b413a6-6877-41cf-abb7-bd6d4f467b11)
2020-11-30 08:33:43,292 DEBUG: Running command: ['virsh', 'destroy', 'kstest-basic-ftp_(14b413a6-6877-41cf-abb7-bd6d4f467b11)']
2020-11-30 08:33:43,563 DEBUG: Running command: ['virsh', 'undefine', 'kstest-basic-ftp_(14b413a6-6877-41cf-abb7-bd6d4f467b11)']
2020-11-30 08:33:43,598 DEBUG: Running command: ['virsh', 'pool-destroy', 'kstest-basic-ftp.ct12lnvh']
2020-11-30 08:33:43,637 DEBUG: Running command: ['virsh', 'pool-undefine', 'kstest-basic-ftp.ct12lnvh']
2020-11-30 08:33:43,671 ERROR: Install failed: Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
2020-11-30 08:33:43,671 ERROR: ERROR: Image creation failed: Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
2020-11-30 08:33:43,671 INFO: RESULT:basic-ftp:6f1f6c43963d:FAILED:Test failed on line: 08:33:33,343 ERR anaconda:packaging: base repo (URL/ftp://ftp.tu-chemnitz.de/pub/linux/fedora/linux/development/rawhide/Everything/$basearch/os/) not valid -- removing it
```

virt-install.log is as before, that's not touched here (and doesn't even use Python's logging, virt-install itself writes that). These are the only two log files now.

**Comment by martinpitt** [comment]
Oops, the report still looks wrong, the "host" value is bogus now. We also don't need that any more.

**Comment by martinpitt** [comment]
https://github.com/rhinstaller/kickstart-tests/actions/runs/391535926 just finished with these commits (as long as we don't have Travis)

**Comment by martinpitt** [comment]
Rebased to current master, to trigger Travis (I bought the paid plan, we have it back!)

**Review by jkonecny12 — APPROVED** [review]
Looks great to me!

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
