### PR TITLE
Add reqpart to raid 1

### PR DESCRIPTION
**Pull request by rvykydal**
The test was missisng in the https://github.com/rhinstaller/kickstart-tests/pull/763

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Review by poncovka — APPROVED** [review]

**Comment by rvykydal** [comment]
Well, the change passes on rawhide, but on daily-iso I am getting
```
09:43:12,910 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:Installing for i386-pc platform.
09:43:12,911 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:grub2-install: warning: ../grub-core/partmap/gpt.c:194:this GPT partition label contains no BIOS Boot Partition; embedding won't be possible.
09:43:12,911 WARNING org.fedoraproject.Anaconda.Modules.Storage:INFO:program:grub2-install: error: embedding is not possible, but this is required for RAID and LVM install.
09:43:12,912 WARNING org.fedoraproject.Anaconda.Modules.Storage:DEBUG:program:Return code: 1
[Uploading virt-install.log…]()

```
 and a Traceback later

**Comment by poncovka** [comment]
I guess the issue is that `reqpart` creates the `biosboot` partition only on one disk. In that case, it is a bug in Anaconda. We could use something like this as a workaround:

```
part biosboot --fstype=biosboot --size=1 --ondisk=vda
part biosboot --fstype=biosboot --size=1 --ondisk=vdb
```

**Comment by poncovka** [comment]
@jstodola @vojtechtrefny Do you think `reqpart` should create both `biosboot` partitions by default? Otherwise, we could just add a new storage validation check that would block the installation in this case.

**Comment by jstodola** [comment]
IMO, `reqpart` should create as many `biosboot` partitions as necessary. If two `biosboot` partitions are needed, they I would expect that the `reqpart` command would create them both.

**Pull request merged**
