### PR TITLE
Disable initial-setup tests on rhel10

### PR DESCRIPTION
**Pull request by rvykydal**
Disable inital-setup-* on rhel10 until gh1111 is fixed.

### CODE REVIEW

**Comment by jkonecny12** [comment]
RHEL-10 won't have Initial Setup. These tests shouldn't be started at all?

**Comment by rvykydal** [comment]
> RHEL-10 won't have Initial Setup. These tests shouldn't be started at all?
> 
> [minimization/content-resolver-input#1025](https://github.com/minimization/content-resolver-input/pull/1025)

Right, updated the PR

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks! :)

**Pull request merged**
