### PR TITLE
Remove --url from the KSTEST_URL variable

### PR DESCRIPTION
**Pull request by poncovka**
The `KSTEST_URL` variable should contain only the URL, so it can be easily used for anything else.

### CODE REVIEW

**Review by VladimirSlavik — COMMENTED** [review]
This removes the ability to use `--mirrorlist` and `--metalink` there, so I would expect some mention of why that is not useful anymore?

**Comment by poncovka** [comment]
> This removes the ability to use `--mirrorlist` and `--metalink` there, so I would expect some mention of why that is not useful anymore?

Some notes:

* We already have to drop `--url` to use the actual url from `KSTEST_URL`.
* I have prepared a bunch of new tests specifically for the `--mirrorlist` and `--metalink` options.
* Without the change, I cannot use `KSTEST_URL` to test the `repo` command, because it is using `--baseurl` instead or `--url`.
* I think we tried to use `--mirrorlist` and `--metalink` in `KSTEST_URL`, but it is too unreliable to use it as a default source.
* We can always modify the kickstart fragments to change to default source to `--mirrorlist` or `--metalink`.
* It is the only environment variable that contains a kickstart option.

@rvykydal, @jkonecny12, what do you think?

**Review by VladimirSlavik — APPROVED** [review]
Thanks, in that case LGTM.

**Review by jkonecny12 — APPROVED** [review]
I like the change. I don't think we are able to use the same link for both (url and mirrorlist) anyway but still this is more versatile solution.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
