### PR TITLE
Mark some of the tests as manual

### PR DESCRIPTION
**Pull request by poncovka**
There are some kickstart tests that I run manually.

**Blocked by:** https://github.com/rhinstaller/kickstart-tests/pull/616

### CODE REVIEW

**Comment by rvykydal** [comment]
Does it mean that the -luks tests can't be reasonably fixed to be automatic ? If they can I'd at least create an issue for it so we don't forgot that there is a chance the test's don't have to be manual.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
> Does it mean that the -luks tests can't be reasonably fixed to be automatic ? If they can I'd at least create an issue for it so we don't forgot that there is a chance the test's don't have to be manual.

@rvykydal, I have created a new issue at https://github.com/rhinstaller/kickstart-tests/issues/628.

**Review by rvykydal — APPROVED** [review]
Thank you.

**Review by VladimirSlavik — APPROVED** [review]

**Pull request merged**
