### PR TITLE
Support running all tests in runner container

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me.
Originally I required tests to be run to be specified explicitly because I was afraid of running all tests (requiring a lot of resources) in the default case (or a case "I don't really know what I am doing").

**Comment by martinpitt** [comment]
> Originally I required tests to be run to be specified explicitly because I was afraid of running all tests

That's a good point. How about we only do that when calling `launch all`? That would mean we could never have an actual test `all.sh`, but that may be an acceptable trade-off.

**Comment by martinpitt** [comment]
@rvykydal: Reworked to explicitly use `launch all`.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
