### PR TITLE
classify: add support for checking of last "anaconda:" line in log

### PR DESCRIPTION
**Pull request by rvykydal**
This check is becoming useful ([675] and [1017] issues in this commit)

### CODE REVIEW

**Comment by rvykydal** [comment]
Example of the script run on a weekly summary (created by Weekly summary workflow https://github.com/rhinstaller/kickstart-tests/actions/workflows/weekly-summary.yml):
```
[rvykydal@prnot4 ~/work/kstests/weekly_reports/test]$ ll
total 0
drwxr-xr-x. 1 rvykydal rvykydal 48 Apr 15 06:50 04-10-2024
drwxr-xr-x. 1 rvykydal rvykydal 48 Apr 15 06:50 04-11-2024
drwxr-xr-x. 1 rvykydal rvykydal 42 Apr 15 06:50 04-12-2024
drwxr-xr-x. 1 rvykydal rvykydal 22 Apr 15 06:50 04-13-2024
drwxr-xr-x. 1 rvykydal rvykydal 62 Apr 15 06:50 04-14-2024
drwxr-xr-x. 1 rvykydal rvykydal 68 Apr 15 06:50 04-15-2024
[rvykydal@prnot4 ~/work/kstests/weekly_reports/test]$ ~/work/git/rvykydal/kickstart-tests.devel/scripts/classify-failures
-------------------------------------------------------------------------------
[675] ([1]) https://github.com/rhinstaller/kickstart-tests/issues/675 The string is also in successful installation, but there is high chance that for test which times out it will be this issue.
#: 8
./04-10-2024/logs-rhel9/flakes/raid-luks-3/1/virt-install.log
00:34:52,008 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-11-2024/logs-rhel9/flakes/network-bootopts-bond-dhcp-httpks/1/virt-install.log
00:39:33,751 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-11-2024/logs-rhel9/flakes/network-static-2-httpks/1/virt-install.log
00:48:44,781 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-12-2024/logs-rhel9/flakes/autopart-luks-4/1/virt-install.log
00:19:54,919 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-12-2024/logs-rhel9/flakes/firewall-disable-with-options/1/virt-install.log
00:10:33,494 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-14-2024/logs-rhel9/flakes/raid-luks-1/1/virt-install.log
00:54:35,400 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-15-2024/logs-rhel9/flakes/autopart-encrypted-3/1/virt-install.log
00:53:39,369 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
--
./04-15-2024/logs-rhel9/flakes/network-bootopts-team-dhcp-httpks/1/virt-install.log
01:08:52,143 INFO anaconda:packaging: Configuring (running scriptlet for): rootfiles-8.1-31.el9.noarch 1628613242 94e7ec73e7998cb2f94f5306fded9be2bc175e5a4c912fd3744f2ca18f2afce1
-------------------------------------------------------------------------------
[992] https://github.com/rhinstaller/kickstart-tests/issues/992 - or it can some more recent issue, the string is pretty generic.
#: 1
./04-12-2024/logs-rhel9/flakes/bindtomac-network-device-mac-pre/1/virt-install.log
23:42:18,413 INFO systemd:Started Process Core Dump (PID 2867/UID 0).
-------------------------------------------------------------------------------
[857] resource to create this format lvmpv is unavailable https://github.com/rhinstaller/kickstart-tests/issues/857
#: 1
./04-12-2024/logs-rhel10/flakes/autopart-encrypted-1/1/virt-install.log
00:17:23,055 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.partitioning.base_partitioning:Storage configuration has failed: resource to create this format lvmpv is unavailable
-------------------------------------------------------------------------------
[930] [939] [794] [782] https://github.com/rhinstaller/kickstart-tests/issues/930
#: 2
./04-14-2024/logs-rhel8/flakes/lvm-luks-3/1/virt-install.log
00:06:03,664 INFO lvmdbusd:json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 4 column 1 (char 34)
--
./04-15-2024/logs-rhel8/flakes/network-bootopts-bond-ks-override/1/virt-install.log
00:55:33,230 INFO lvmdbusd:json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 4)
-------------------------------------------------------------------------------
[984] https://github.com/rhinstaller/kickstart-tests/issues/984
#: 1
./04-12-2024/logs-rhel9/flakes/bindtomac-network-static-2-httpks/1/kstest.log
2024-04-11 23:35:52,910 INFO: RESULT:bindtomac-network-static-2-httpks:36879ed2518e:FAILED:Test failed on line: 23:35:50,480 CRIT anaconda:Anaconda crashed on signal 11
-------------------------------------------------------------------------------
[907] https://github.com/rhinstaller/kickstart-tests/issues/907
#: 2
./04-11-2024/logs-daily-iso/flakes/ui_text_noninteractive/1/virt-install.log
23:38:10,455 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.partitioning.base_partitioning:Storage configuration has failed: No usable disks.
--
./04-13-2024/logs-rhel10/flakes/ui_text_interactive/1/virt-install.log
00:00:51,813 WARNING org.fedoraproject.Anaconda.Modules.Storage:ERROR:anaconda.modules.storage.partitioning.base_partitioning:Storage configuration has failed: No usable disks.
-------------------------------------------------------------------------------
[1017] https://github.com/rhinstaller/kickstart-tests/issues/1017
#: 3
./04-10-2024/logs-daily-iso/flakes/anaconda-conf/1/virt-install.log
00:03:49,685 DEBUG anaconda:anaconda: ui.gui.hubs: kickstart installation, spoke Installation Source is ready
--
./04-12-2024/logs-rhel10/flakes/autopart-encrypted-1/1/virt-install.log
00:17:25,986 DEBUG anaconda:anaconda: ui.gui.hubs: kickstart installation, spoke Installation Source is ready
--
./04-15-2024/logs-daily-iso/flakes/network-bootopts-noautodefault/1/virt-install.log
01:36:43,739 DEBUG anaconda:anaconda: ui.gui.hubs: kickstart installation, spoke Installation Source is ready
[rvykydal@prnot4 ~/work/kstests/weekly_reports/test]$ 
```

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. However, I think it would be better to use 

https://github.com/fedora-copr/logdetective

And try to do this "smart way".

Definitely future improvement.

**Review by jikortus — APPROVED** [review]
Looks useful to me! :-)

**Comment by rvykydal** [comment]
> Looks good to me. However, I think it would be better to use
> 
> https://github.com/fedora-copr/logdetective
> 
> And try to do this "smart way".
> 
> Definitely future improvement.

Of course this is old good non-ai way. But there were absolutely no resources to play with something like that.

**Pull request merged**
