### PR TITLE
Update the repo-install test

### PR DESCRIPTION
**Pull request by poncovka**
Anaconda generates repo files in the same format as DNF since anaconda-36.17-1.

**Depends on:** https://github.com/rhinstaller/anaconda/pull/3811

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by poncovka** [comment]
> Why not just insert "` ?`" at the right places in the script?

Do you suggest to change the regexes instead? It would work, but I would prefer to make sure that we use the new format.

**Comment by VladimirSlavik** [comment]
Yes, that was the idea. But I can see why you want to special-case that.

**Review by VladimirSlavik — APPROVED** [review]

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
