### PR TITLE
Enable RDP test on Fedora

### PR DESCRIPTION
**Pull request by jkonecny12**
It was implemented by https://github.com/rhinstaller/anaconda/pull/5829

### CODE REVIEW

**Comment by jkonecny12** [comment]
Tested by https://github.com/rhinstaller/anaconda/actions/runs/11017713395/job/30596297336

**Review by KKoukiou — APPROVED** [review]

**Comment by rvykydal** [comment]
> /test-tmt

```
06:40:06,736 ERR anaconda:Traceback (most recent call last):
06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/threads.py", line 280, in run
06:40:06,736 ERR anaconda:    threading.Thread.run(self)
06:40:06,736 ERR anaconda:    ~~~~~~~~~~~~~~~~~~~~^^^^^^
06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/threading.py", line 992, in run
06:40:06,736 ERR anaconda:    self._target(*self._args, **self._kwargs)
06:40:06,736 ERR anaconda:    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/site-packages/pyanaconda/gnome_remote_desktop.py", line 173, in _get_hostname_in_thread
06:40:06,736 ERR anaconda:    hinfo = socket.gethostbyaddr(ip)
06:40:06,736 ERR anaconda:TypeError: gethostbyaddr() argument 1 must be str, bytes or bytearray, not None
```

**Comment by KKoukiou** [comment]
@jkonecny12 can you check this when you have time https://github.com/rhinstaller/kickstart-tests/pull/1309 ?

**Comment by M4rtinK** [comment]
Looks like it found something, cool. :)

**Comment by jkonecny12** [comment]
Added code to avoid stopping the test on Gdk known error.

**Comment by jkonecny12** [comment]
> > /test-tmt
> 
> ```
> 06:40:06,736 ERR anaconda:Traceback (most recent call last):
> 06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/site-packages/pyanaconda/core/threads.py", line 280, in run
> 06:40:06,736 ERR anaconda:    threading.Thread.run(self)
> 06:40:06,736 ERR anaconda:    ~~~~~~~~~~~~~~~~~~~~^^^^^^
> 06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/threading.py", line 992, in run
> 06:40:06,736 ERR anaconda:    self._target(*self._args, **self._kwargs)
> 06:40:06,736 ERR anaconda:    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 06:40:06,736 ERR anaconda:  File "/usr/lib64/python3.13/site-packages/pyanaconda/gnome_remote_desktop.py", line 173, in _get_hostname_in_thread
> 06:40:06,736 ERR anaconda:    hinfo = socket.gethostbyaddr(ip)
> 06:40:06,736 ERR anaconda:TypeError: gethostbyaddr() argument 1 must be str, bytes or bytearray, not None
> ```

I wasn't able to reproduce this issue :(

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
