### PR TITLE
Test TUI and GUI of the initial setup in the smoke tests

### PR DESCRIPTION
**Pull request by poncovka**
The reboot tests can be run from pull requests in the Anaconda repository now.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. I just wonder if one of these tests is not enough for smoke?

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

I think the price is ok. Kickstart tests are manually triggered anyway...

**Comment by poncovka** [comment]
> Looks good to me. I just wonder if one of these tests is not enough for smoke?

We run different code in TUI and GUI.

**Review by rvykydal — APPROVED** [review]
Looks good to me. Hope rebooting will not be too flaky.

**Pull request merged**
