### PR TITLE
Grab GitHub notifications for periodic workflows

### PR DESCRIPTION
**Pull request by jkonecny12**
Unfortunately, GitHub will sent notifications about failures for on:schedule workflows just to the last person who did some changes to the workflow. :(

Because of that it would be great to get the notifications on me so I'm going to steal them by this PR! HAHAHAHAHAHA!

### CODE REVIEW

**Review by martinpitt — APPROVED** [review]
Officially handing over! :handshake:

**Review by poncovka — APPROVED** [review]
This is so silly :-D

**Review by VladimirSlavik — APPROVED** [review]
All your file are belong to us!

**Pull request merged**
