### PR TITLE
Fix rhel 8 daily runs

### PR DESCRIPTION
**Pull request by martinpitt**
These currently [fail](https://github.com/rhinstaller/kickstart-tests/actions?query=workflow%3A%22Build+and+test+daily+RHEL+boot.iso%22) because of issue #448. I have not yet found the root cause of this, but these failures are highly annoying as the auto-retried timeouts blow up the test run time from some 45 mins to 2½ hours.

The first commit is some cleanup which is good to have in any case IMHO. The second is a workaround that just uses the "ens*" network names for this scenario until we adjust the lorax invocation to do whatever the official image does.

I manually triggered tests from this branch for the:

 - [x] [rhel 8 daily workflow](https://github.com/rhinstaller/kickstart-tests/runs/1549172042?check_suite_focus=true)
 - [x] [usual nightly scenarios](https://github.com/rhinstaller/kickstart-tests/actions/runs/420382189)

(the latter to ensure that the first commit does not break anything). Until these finish, I keep this as blocked, but review is already appreciated of course.

### CODE REVIEW

**Comment by martinpitt** [comment]
Travis  and the rhel and fedora daily boot.iso scenarios all succeeded; the two others (rhel8 and rawhide) look promising, so I'm reasonably confident that this works. Ready to review.

**Comment by martinpitt** [comment]
Fixed some typos in the commit message. No functional change thus not re-running workflows again.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Review by poncovka — APPROVED** [review]
Looks good to me. Thanks!

**Comment by martinpitt** [comment]
Test runs finished. rawhide, fedora+rhel daily-iso are green, and rhel8 only failed on #447. So this is good to go.

**Comment by VladimirSlavik** [comment]
I can't meaningfully comment on the changes, but thank you for fixing the docs too!

**Pull request merged**
