### PR TITLE
Add the missing reqpart command

### PR DESCRIPTION
**Pull request by poncovka**
Add the `reqpart` command to all tests with custom partitioning. It will ensure
creation of the `biosboot` partition if required by the installed system.

### CODE REVIEW

**Comment by poncovka** [comment]
Some of the tests might require additional changes in the `%post` scripts. I didn't run all of them, so I suggest to merge this and open another pull request if necessary.

**Comment by jkonecny12** [comment]
I wonder is this a behavior change of Anaconda or a side effect?

**Review by rvykydal — APPROVED** [review]
Thank you.

**Review by jkonecny12 — APPROVED** [review]
Thanks, my question was already answered.

The issue is that we have switched to `GPT` by default recently (there is a Fedora change about that).

**Pull request merged**
