### PR TITLE
Switch rhel10 platform to centos images (gh#1190)

### PR DESCRIPTION
**Pull request by rvykydal**
Latest rhel10 nightly is broken
https://github.com/rhinstaller/kickstart-tests/issues/1190

### CODE REVIEW

**Comment by marusak** [comment]
> [radek wrote](https://github.com/rhinstaller/kickstart-tests/issues/1190#issuecomment-2120121082) workaround for the issue, use "%packages --ignoremissing"

Wouldn't that be better?

**Comment by rvykydal** [comment]
> > [radek wrote](https://github.com/rhinstaller/kickstart-tests/issues/1190#issuecomment-2120121082) workaround for the issue, use "%packages --ignoremissing"
> 
> Wouldn't that be better?

Yes perhaps, I think it is for a separate PR and maybe some discussion, but indeed instead of a few ignoremissing tests we could have a few non-ignoremissing tests. We need to be a bit careful here with such a massive change but in general makes sense to me.

**Comment by jstodola** [comment]
The problem with missing `kdump-utils` is fixed in the latest RHEL-10 nightly RHEL-10.0-20240520.72, is this change still needed?

**Comment by rvykydal** [comment]
Thank you for heads-up, closing.

**Pull request closed without merging**
