### PR TITLE
Add tests for the inst.disklabel boot option

### PR DESCRIPTION
**Pull request by poncovka**
Check the type of the partition table created during the installation.

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by poncovka** [comment]
Updated. All these tests should be skipped on RHEL 8 and RHEL 9 due to the unsupported `inst.disklabel` boot option.

**Comment by rvykydal** [comment]
I think it would be great to have an option to run our daily scenarios (ie rhel8, rhel9, daily-iso) with selected tests on a PR like this.

**Comment by rvykydal** [comment]
@poncovka I guess the build failed because of rawhide not having the required changes. They should be in now but I am not able to re-run the check.

**Pull request merged**
