### PR TITLE
Generate report in runner container

### LINKED ISSUE #398: Run run_report.sh script on containerized kstest batch completion
If running multiple containerized kickstart tests via `containers/runner/launch` it might be unclear what the overall results of the test batch were, without manually checking the results in `data` directory. 

It would be good if a summary listing was displayed of all the tests that have been run in the given batch and their result (SUCCESS/FAILED + some short summary why the tests failed if it did). Then one would have to inspect results for just the failed tests.

Thankfully we already have a tool just for that in `scripts/run_report.sh`. This expects to be run on a concatenated log output from the kickstart test runner and will enumerate all the tests that have been run and their results. The output looks like this:

```

        TEST                                                    | HOST            | RESULT     | EXPLANATION
        --------------------------------------------------------+-----------------+------------+-------------------------------------------
        btrfs-1                                                 | mk-kstest-2     | FAILED     | error in log: Call Trace::
        btrfs-2                                                 | mk-kstest-1     | FAILED     | error in log: Call Trace::
        lvm-1                                                   | mk-kstest-1     | SUCCESS    |
        lvm-cache-1                                             | mk-kstest-1     | SUCCESS    |
        default-fstype                                          | mk-kstest-2     | SUCCESS    |
        encrypt-device                                          | mk-kstest-1     | SUCCESS    |
        escrow-cert                                             | mk-kstest-2     | SUCCESS    |
        lvm-2                                                   | mk-kstest-2     | SUCCESS    |
        lvm-cache-2                                             | mk-kstest-2     | SUCCESS    |
        lvm-raid-1                                              | mk-kstest-1     | SUCCESS    |
        nosave-all                                              | mk-kstest-2     | FAILED     | Validation failed with return code 1
        tmpfs-fixed_size                                        | mk-kstest-2     | SUCCESS    |
        reqpart                                                 | mk-kstest-1     | SUCCESS    |
        encrypt-swap                                            | mk-kstest-2     | SUCCESS    |
        raid-1                                                  | mk-kstest-2     | SUCCESS    |
        lvm-thinp-2                                             | mk-kstest-1     | SUCCESS    |
        lvm-thinp-1                                             | mk-kstest-1     | SUCCESS    |
        autopart-encrypted-2                                    | mk-kstest-2     | SUCCESS    |
        autopart-encrypted-3                                    | mk-kstest-2     | SUCCESS    |
        autopart-nohome                                         | mk-kstest-2     | SUCCESS    |
        bootloader-1                                            | mk-kstest-2     | SUCCESS    |
        autopart-encrypted-1                                    | mk-kstest-1     | SUCCESS    |
        bootloader-3                                            | mk-kstest-1     | SUCCESS    |
        autopart-fstype                                         | mk-kstest-1     | SUCCESS    |
        bootloader-2                                            | mk-kstest-1     | SUCCESS    |
        clearpart-1                                             | mk-kstest-2     | SUCCESS    |
        bootloader-4                                            | mk-kstest-2     | SUCCESS    |
        bootloader-5                                            | mk-kstest-2     | SUCCESS    |
        clearpart-3                                             | mk-kstest-1     | SUCCESS    |
        ignoredisk-1                                            | mk-kstest-1     | SUCCESS    |
        clearpart-2                                             | mk-kstest-2     | SUCCESS    |
        clearpart-4                                             | mk-kstest-1     | SUCCESS    |
        mountpoint-assignment-1                                 | mk-kstest-2     | SUCCESS    |
        ignoredisk-2                                            | mk-kstest-1     | SUCCESS    |
        mountpoint-assignment-2                                 | mk-kstest-2     | SUCCESS    |
        autopart-luks-1                                         | mk-kstest-2     | SUCCESS    |
        autopart-luks-4                                         | mk-kstest-2     | SUCCESS    |
        autopart-luks-3                                         | mk-kstest-1     | SUCCESS    |
        autopart-luks-2                                         | mk-kstest-1     | SUCCESS    |
        autopart-luks-5                                         | mk-kstest-1     | SUCCESS    |
         
        ===================================================================================================================================
        Test suite for kickstart tests summary:
        ===================================================================================================================================
        # TOTAL:      40
        # PASS:       37
        # FAILED:     3
        # TIMED OUT:  0
        ===================================================================================================================================


```
So running this script on concatenated log output from the containerized test run would be very useful. 

Also, the script will work on *any* set of concatenated kickstart test runner log output, so it might be even possible to use it for batch progress monitoring by running it on the intermediate concatenated log output, to see how the batch is progressing.

### PR DESCRIPTION
**Pull request by martinpitt**
Fixes #398

### CODE REVIEW

**Comment by martinpitt** [comment]
I added an additional dummy commit that touches lvm-cache-1. That's a known failed test, so let's make sure it looks alright in the report.

**Comment by martinpitt** [comment]
The run with the dummy commit [failed as expected](https://travis-ci.com/github/rhinstaller/kickstart-tests/builds/199251116), and the summary looks fine.

I dropped the dummy commit, it should succeed now and still generate a good report.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks a lot! :)

**Pull request merged**
