### PR TITLE
Update probing iso for rhel 10

### PR DESCRIPTION
**Pull request by rvykydal**
Intermediate ext4 filesystem was removed in RHEL 10 image.

https://fedoraproject.org/wiki/Changes/OptimizeSquashFSOnDVDByRemovingEXT4FilesystemImageLayer

### CODE REVIEW

**Comment by rvykydal** [comment]
The failure in /test-platforms test is unrelated to this issue (it is https://issues.redhat.com/browse/RHEL-34023). Actually having any results shows that this issue is fixed.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Pull request merged**
