### PR TITLE
New test: rpm-ostree-container-luks

### PR DESCRIPTION
**Pull request by jikortus**
It is built on top of @rvykydal's PR https://github.com/rhinstaller/kickstart-tests/pull/1116 and might need to be reshuffled a bit/rebased (after PR https://github.com/rhinstaller/kickstart-tests/pull/1116 gets merged) to be suitable for merging into master.

### CODE REVIEW

**Comment by jikortus** [comment]
@rvykydal, sorry for the delay - I rebased the PR and retested it with RHEL-9 and Fedora, hope it will be OK :-).

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Review by M4rtinK — APPROVED** [review]
Looks good to me, thanks a lot! :)

**Comment by jikortus** [comment]
@rvykydal @M4rtinK Thank you for the reviews! Could you please merge the PR now that it got an approval from you? Thank you!

**Pull request merged**
