### PR TITLE
Use the VirtIO disk bus

### PR DESCRIPTION
**Pull request by poncovka**
It should be faster than SATA and solve some of our issues.

Related: rhbz#1974337

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
LGTM, thank you.

I wonder if there is a danger of excluding some code paths with this? I could not find anything virtio-specific in Anaconda and Blivet, so probably not in the code we intend to test.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Comment by poncovka** [comment]
Tested with a small subset of tests on rawhide, RHEL 8 and RHEL 9. It fixes RHEL 9 tests that are not using the LVM partitioning. Remaining tests are failing because of the `no operating system was found on this disk` error of the `virt-copy-out` when we try to copy out logs and results. I suggest to merge this PR.

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
