### PR TITLE
Run fixed tests failing for kickstart in stage2 changes on rhel8 again

### PR DESCRIPTION
**Pull request by rvykydal**
The tests marked with the tag are fixed in these PRs:
* [x] https://github.com/rhinstaller/kickstart-tests/pull/434
* [x] https://github.com/rhinstaller/kickstart-tests/pull/433
* [x] https://github.com/rhinstaller/kickstart-tests/pull/432
* [x] https://github.com/rhinstaller/kickstart-tests/pull/441
* [x] https://github.com/rhinstaller/kickstart-tests/pull/440
* [x] https://github.com/rhinstaller/kickstart-tests/pull/438
* [x] https://github.com/rhinstaller/kickstart-tests/pull/437
* [x] https://github.com/rhinstaller/kickstart-tests/pull/442

### CODE REVIEW

**Comment by martinpitt** [comment]
This doesn't seem quite ready yet? `network-device-mac.sh` still has that testtype.

**Comment by rvykydal** [comment]
@martinpitt thank you, I should have checked that. I've added a commit to remove it.

**Comment by rvykydal** [comment]
@martinpitt, I am going to open a PR to mark [bindtomac]-bridged-bond-httpks as knownfailure and create a ticket to investigate as it seems to be failing beyond flakiness both on old and new infra.

**Review by martinpitt — APPROVED** [review]
Dekuji!

**Comment by rvykydal** [comment]
> @martinpitt, I am going to open a PR to mark [bindtomac]-bridged-bond-httpks as failing and create a ticket to investigate as it seems to be failing beyond flakiness both on old and new infra (on rhel-8).

https://github.com/rhinstaller/kickstart-tests/pull/450

**Pull request merged**
