### PR TITLE
Add basic tests for the url and repo commands

### PR DESCRIPTION
**Pull request by poncovka**
* Test the `--url`, `--metalink` and `--mirrorlist` options of the `url` command.
* Test the `--baseurl`, `--metalink`, `--mirrorlist` and `--install `options of the `repo` command.

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by rvykydal — APPROVED** [review]
Looks good to me, I just wonder if we should use
```
%ksappend  payload/default_packages.ks
```
instead of
```
%packages
%end
```

**Comment by poncovka** [comment]
@rvykydal, good point! I have updated the PR.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.

**Pull request merged**
