### PR TITLE
Master fix driverdisk test

### LINKED ISSUE #605: driverdisk-disk tests timing out with no virt-install.log
The issue was imported from bugzilla to track https://bugzilla.redhat.com/show_bug.cgi?id=1973156 here.

A kickstart test is failing.

Run:  Daily run #217 (also before) (https://github.com/rhinstaller/kickstart-tests/actions/runs/944542914)
Scenario: daily-iso
Test: driverdisk-disk

The test has been failing with TIMEOUT as a flake (ie second try passed) for some time but recently it fails as "failed" (second try fails as well) more often.

Given virt-install.log is empty I guess it hangs in initramfs.
I was not able to reproduce the failure locally.

### PR DESCRIPTION
**Pull request by jkonecny12**
The problem was that cdrom couldn't be type of 'virtio' but 'virtio' type was added automatically. Change the solution that when the disk string starts with `path=` it will not change this string and allow complete specification.

Closes #605.

### CODE REVIEW

**Comment by jkonecny12** [comment]
Merged commits together.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me. Thank you!

**Review by poncovka — APPROVED** [review]

**Review by M4rtinK — APPROVED** [review]
Looks good to me.

**Comment by jkonecny12** [comment]
*UPDATED:*
* Rebased to resolve conflict.

**Pull request merged**
