### PR TITLE
Add an UEFI test (reboot-uefi) to coverage and smoke groups

### PR DESCRIPTION
**Pull request by rvykydal**
Resolves: INSTALLER-4061
A modification of `reboot` test.

### CODE REVIEW

**Comment by rvykydal** [comment]
/test-os-variants --testtype smoke --skip-testtypes skip-on-rhel-10

**Review by jstodola — APPROVED** [review]
It looks fine.
If I should suggest an enhancement, it would be nice to check that the system is really running in UEFI mode - either during the installation or after reboot. Perhaps just a simple execution of `efibootmgr` should be enough (it fails on non-UEFI systems).

**Comment by rvykydal** [comment]
I should mention that this is a modification of `reboot` test.

**Comment by rvykydal** [comment]
> It looks fine. If I should suggest an enhancement, it would be nice to check that the system is really running in UEFI mode - either during the installation or after reboot. Perhaps just a simple execution of `efibootmgr` should be enough (it fails on non-UEFI systems).

@jstodola updated

**Review by jstodola — APPROVED** [review]
It looks good, thanks.

**Pull request merged**
