### PR TITLE
Master improve bond and team tests

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
The name of the branch is misleading, this is only for bond tests, I've updated team tests in a separate PR: https://github.com/rhinstaller/kickstart-tests/pull/54

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
I am going to rebase this PR upon
https://github.com/rhinstaller/kickstart-tests/pull/63
when/if it gets merged.

**Comment by rvykydal** [comment]
Rebased on master with @KSINCLUDE@

**Pull request merged**
