### PR TITLE
Add network ifname boot option test

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by jkonecny12** [comment]
The CI is getting this result:

```
*** Failed check: ifcfg file /etc/sysconfig/network-scripts/ifcfg-ens4 exists                                                                                                                                    
*** Failed check: ifcfg file /etc/sysconfig/network-scripts/ifcfg-ens4 exists
```

**Comment by rvykydal** [comment]
Fixed by creating rhel/fedora version.
Also I fixed the rename of the test (ifname -> ifname-httpks)

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
The CI check fail is expected:
https://bugzilla.redhat.com/show_bug.cgi?id=1457215

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Comment by rvykydal** [comment]
jenkins, test this please

**Pull request merged**
