### PR TITLE
Update dhcpclass test for RHEL 9 fix

### PR DESCRIPTION
**Pull request by rvykydal**
The issue has been resolved on RHEL 9.

### CODE REVIEW

**Comment by rvykydal** [comment]
Re-run the test when https://issues.redhat.com/browse/RHEL-30406 gets into nightly composes.

**Comment by rvykydal** [comment]
> Re-run the test when https://issues.redhat.com/browse/RHEL-30406 gets into nightly composes.

Succeeded

**Review by jstodola — APPROVED** [review]

**Review by jkonecny12 — APPROVED** [review]
A bit late but still 😃

**Pull request merged**
