### PR TITLE
Ignore also /dev when checking wrong SELinux contexts

### LINKED ISSUE #607: Failing selinux-contexts on rhel-9: Would relabel /dev/vcsa5 ...
The selinux-contexts test is causing flakes and sometimes failures on rhel-9
```
2021-10-27 00:17:27,053 DEBUG: Failed to run subprocess: '['/opt/kstest/kickstart-tests/scripts/launcher/lib/launcher_interface.sh', '-i', '/opt/kstest/data/images/boot.iso', '-k', '1', '-w', '/var/tmp/kstest-selinux-contexts.2021_10_27-00_05_30.8oaqnh93', '-t', '/opt/kstest/kickstart-tests/selinux-contexts.sh', 'validate']'
stdout:
*** System has started with errors:
Would relabel /dev/vcsa5 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsu5 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcs5 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsa4 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsu4 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcs4 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsa3 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsu3 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcs3 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsa2 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0
Would relabel /dev/vcsu2 from system_u:object_r:device_t:s0 to system_u:object_r:tty_device_t:s0

2021-10-27 00:17:27,053 INFO: RESULT:selinux-contexts:967e24590dfd:FAILED:Validation failed with return code 1

```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/7451932/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/7451933/virt-install.log)

### PR DESCRIPTION
**Pull request by VladimirSlavik**
Somehow this path disappeared during changes to the test with no explanation.

Closes #607

### CODE REVIEW

**Comment by VladimirSlavik** [comment]
@jstodola, can you please review this? The previous change that removed this path is neither logical nor documented, but I think we worked on this together back then, so you might remember something I don't.

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you.
But I would wait for @jstodola to confirm.

**Comment by VladimirSlavik** [comment]
One more thought. Perhaps the test could be made more robust by adapting the code to automatically detect filesystem types and boundaries, so that it understands what should be ignored. IIRC the SELinux scripts that run after `.autorelabel` is found during boot/startup contain a lot of logic dedicated to this exact problem. However I think it's too much work for too little gain right now.

**Comment by jkonecny12** [comment]
Hmm, running `restorecon` on dev seems like something you shouldn't do. The `/dev` contains special or device files. These shouldn't be persistent which means that you should not need to fix context on them...

**Comment by VladimirSlavik** [comment]
- The `-n` options makes it a dry run, almost same as with `git clean`. It only lists what would be relabeled instead of really doing it.
- The `-e something` is to exclude/ignore paths, so it will not be touched. The real path is the first one (`/`) before the bunch of `-e`

**Review by jstodola — APPROVED** [review]
I agree, it doesn't make much sense to check `/dev` as part of anaconda testing, the content is not created by the installer. `/dev` is excluded in our downstream tests as well.

**Comment by jkonecny12** [comment]
>     * The `-n` options makes it a dry run, almost same as with `git clean`. It only lists what would be relabeled instead of really doing it.
> 
>     * The `-e something` is to exclude/ignore paths, so it will not be touched. The real path is the first one (`/`) before the bunch of `-e`

Ohh, sorry I missed the arguments you are passing there. My bad.

**Review by jkonecny12 — APPROVED** [review]
Looks good to me.

**Review by rvykydal — APPROVED** [review]
Looks good to me.

**Pull request merged**
