### PR TITLE
Add test for bootupd/bootc ostree containers

### PR DESCRIPTION
**Pull request by VladimirSlavik**
WIP, needs some more checking...

### CODE REVIEW

**Review by poncovka — COMMENTED** [review]
Hi! I think the main information that want from this test is a confirmation that the final system is bootable. Can you reuse here some parts of the `reboot` test to verify that?

**Comment by VladimirSlavik** [comment]
Still WIP, can't get the validation to work.

**Comment by jikortus** [comment]
Here's a couple of findings related to earlier discussions with @VladimirSlavik which should likely be taken into account when finishing the test:

- The container image used in the test doesn't likely support BTRFS by default (no dracut module in initrd), so it will likely fail to mount root fs.
- `/boot` partition may need to have a `boot` label set, so that kernel and initrd files are properly found by GRUB.
- not sure if GRUB will find kernel and initrd files if `/boot` doesn't reside on a separate partition

**Comment by jikortus** [comment]
Taking over the test development from Vladimir, will continue working on it after some higher priority tasks I've on my plate right now are done.

**Comment by rvykydal** [comment]
FYI, there is some tests renaming / consolidation undergoing: https://github.com/rhinstaller/kickstart-tests/pull/1054

**Comment by rvykydal** [comment]
Follow-up in https://github.com/rhinstaller/kickstart-tests/pull/1096

**Pull request closed without merging**
