### PR TITLE
Add dependencies required to run mkdud.py and make-addon-pkgs.py

### PR DESCRIPTION
**Pull request by rvykydal**
Currently used by proxy-* and driverdisk-disk tests.

### CODE REVIEW

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Comment by VladimirSlavik** [comment]
Can you please adjust also `README.rst` and `scripts/install_dependencies_fedora.sh` ?

**Comment by rvykydal** [comment]
> Can you please adjust also `README.rst` and `scripts/install_dependencies_fedora.sh` ?

Good idea, added. (We should have single point of truth, but for now I'll add to both places.)

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

This should solve the `addrepo` test too.

**Pull request merged**
