### PR TITLE
Improve network team tests - check created slaves and options.

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by jkonecny12** [comment]
jenkins, test this please

**Comment by jkonecny12** [comment]
It looks like something here causing:
```
scripts/run_kickstart_tests.sh: line 185: [: team-pre.sh: binary operator expected
```

**Comment by rvykydal** [comment]
I am going to rebase this PR upon
https://github.com/rhinstaller/kickstart-tests/pull/63
when/if it gets merged.

**Comment by rvykydal** [comment]
Rebased on master with @KSINCLUDE@

**Pull request merged**
