### PR TITLE
Replace 2 leftover occurences of is_rhel8 function

### PR DESCRIPTION
**Pull request by rvykydal**
The fuction was renmoved in
commit 8cb666a60b53e3a7b85be36738e16f4bfdb686f3

### CODE REVIEW

**Review by jstodola — APPROVED** [review]

**Comment by rvykydal** [comment]
Tests reveal that needs also a fix of authselect-not-set on rhel8 and rhel9 - now that they work :)

**Review by jkonecny12 — APPROVED** [review]
LGTM!

**Pull request merged**
