### PR TITLE
linchpin: add nightly tests configuration to examples

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Comment by rvykydal** [comment]
I'd prefer to keep them, they are useful for us and they don't hurt anybody else - they are just real world examples.

**Comment by jkonecny12** [comment]
We really should not expose parts of our internal infrastructure anywhere, it's better to be over-protective than having to solve problems when it's there. It's not useful for outside people, if you replace all the links with example.com it will be more obvious that community can't use it.

**Comment by M4rtinK** [comment]
I think we should be able to use the public links for the Fedora repos at least. And maybe the CentOS 8 repo links for the RHEL example ?

**Comment by rvykydal** [comment]
Okay, I think you are right, these are not examples but real configurations which don't belong here.

**Pull request closed without merging**
