### PR TITLE
Extend payload group

### PR DESCRIPTION
**Pull request by jkonecny12**
Extend the `payload` group to all payload related tests and remove old `method` group which is outdated and confusing.

### CODE REVIEW

**Review by M4rtinK — APPROVED** [review]
Looks good to me. :)

**Review by rvykydal — APPROVED** [review]
Looks good to me, thank you!

**Comment by jkonecny12** [comment]
Tests are failing but this PR is not modifying tests directly so it seems to be something different. Also test-os-variants is running even known-issue and similar tests.

**Pull request merged**
