### PR TITLE
Add dnf5-unstable repo temporarily

### PR DESCRIPTION
**Pull request by rvykydal**
dnf.conf was moved from dnf-data to dnf5 so we need to add the dnf5-unstable repository until dnf5 is stable

https://github.com/rhinstaller/kickstart-tests/actions/runs/5182410192/jobs/9339168075

### CODE REVIEW

**Comment by rvykydal** [comment]
Need to test it.

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

I guess we're assuming the "soonish" might become "longish" so we're covered anyway?

**Review by jkonecny12 — APPROVED** [review]
LGTM, thanks!

**Comment by rvykydal** [comment]
Tested here: https://github.com/rvykydal/kickstart-tests/actions/runs/5188945086/jobs/9353252388

**Pull request merged**
