### PR TITLE
Bond rhel 38451

### PR DESCRIPTION
**Pull request by rvykydal**
Updates virtual network devices tests for https://github.com/rhinstaller/anaconda/pull/5703

### CODE REVIEW

**Comment by rvykydal** [comment]
Rawhide failure is ok for now, the change is in the latest build and daily-iso.
The PR will fix daily tests.

**Review by jkonecny12 — APPROVED** [review]
I think that the last two commits could be merged but I don't insist on that. Looks good to me.

**Review by jstodola — APPROVED** [review]

**Comment by rvykydal** [comment]
Thank you for the reviews guys!

**Pull request merged**
