### PR TITLE
Remove dracut-visible-arnings check

### PR DESCRIPTION
**Pull request by r0x0d**
We removed the deprecated warnings for inst.* in anaconda, thus, this test will always assert for something that will not appear anymore

Anaconda PR: https://github.com/rhinstaller/anaconda/pull/5723

### CODE REVIEW

**Review by KKoukiou — APPROVED** [review]
@M4rtinK can you please take a look as well?

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks!

**Review by rvykydal — COMMENTED** [review]
@jkonecny12 shouldn't we rather modify the test so that is still tests (IIUIC it was the purpose of https://github.com/rhinstaller/kickstart-tests/commit/0f30bea02182d9b29ef350ec442092a3f5d77939) the feature: https://github.com/rhinstaller/anaconda/pull/3533 ?

**Comment by jkonecny12** [comment]
@rvykydal if you mean to modify the test to test if the warnings are not showed then I think this is better solution. Let's spare resources of our kickstart tests here. If the warning was missed somewhere than it is not a critical issue but we would leave this test running for-ever.

Do you have some specific reason why would you leave it here what I might be missing?

**Review by rvykydal — APPROVED** [review]

**Comment by rvykydal** [comment]
I just wanted to have a (generic) test for the feature used for the warnings but yes, let's handle it out of scope of this PR, if at all.

**Pull request merged**
