### PR TITLE
Test the --ignorebroken option of the %packages section

### PR DESCRIPTION
**Pull request by poncovka**
Add a new test for `%packages --ignorebroken`.

### CODE REVIEW

**Review by rvykydal — APPROVED** [review]
Thank you.

**Review by VladimirSlavik — COMMENTED** [review]
I'm not acking (yet) because I can't tell which package should be installed, or if that matters at all.

**Comment by poncovka** [comment]
> I'm not acking (yet) because I can't tell which package should be installed, or if that matters at all.

DNF will skip the optional package. That was surprising to me, because I was expecting the conflicting package to be skipped. Based on that, the test only checks that exactly one of these packages is installed at the end, so we don't have to rely on the DNF logic and interpretation.

**Comment by VladimirSlavik** [comment]
Thank you! Maybe that should be written in the test? :-)

**Comment by poncovka** [comment]
Updated.

**Review by VladimirSlavik — APPROVED** [review]
Thank you!

**Review by jkonecny12 — APPROVED** [review]
Looks good to me. Thanks for adding this.

**Pull request merged**
