### PR TITLE
Use redirector for rawhide repository

### PR DESCRIPTION
**Pull request by rvykydal**

### CODE REVIEW

**Review by VladimirSlavik — APPROVED** [review]
Looks good to me.

Notes: I guess there isn't any way to specify the geo like https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64&country=US :( Also, pitti warned that some of the mirrors are less reliable, which was why he hardcoded a particular one.

**Comment by rvykydal** [comment]
> Looks good to me.
> 
> Notes: I guess there isn't any way to specify the geo like https://mirrors.fedoraproject.org/mirrorlist?repo=rawhide&arch=x86_64&country=US :( 
Interesting idea,
http://download.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/?&country=US works for me in the browser so we could perhaps try to use it ?
> Also, pitti warned that some of the mirrors are less reliable, which was why he hardcoded a particular one.
Yes, it was also mentioned in a comment. I returned to the redirector because the mirror we are using for the last few days stopped working yesterday.

**Review by poncovka — APPROVED** [review]
I like this change.

**Comment by VladimirSlavik** [comment]
I actually wonder if specifying the geo is a good idea. I think it's auto-detected, so maybe it *is* better to leave it out, so that if we move the workers or something, it works well.

**Pull request merged**
