### PR TITLE
Checks whether OSCAP spoke is disabled

### PR DESCRIPTION
**Pull request by marta-lewandowska**
Test to check that OSCAP spoke is not shown if the OSCAP DBus
module is disabled. (RTT-3983)

### CODE REVIEW

**Comment by marta-lewandowska** [comment]
Please review this new test which automates https://bugzilla.redhat.com/show_bug.cgi?id=2018954
Thank you! :)

**Review by VladimirSlavik — COMMENTED** [review]
Thanks! I can see the value of such test, but I don't think this would work. It fails on any message that comes from addons. What makes it distinguish between Kdump and Oscap? How do we know the message actually means the modules are activated?

So, either make the grepping more specific, or rename this to be about disabled addons. Also, please link the BZ from commit too, just to make the information available.

**Comment by marta-lewandowska** [comment]
Added OSCAP to the grep to make it more specific. It is a good idea!

**Comment by jstodola** [comment]
I think it would be more beneficial to make the test more general, so that it can detect if any addon started, not just the oscap addon.

**Comment by marta-lewandowska** [comment]
Generalized and renamed the test. Rewrote commit message to reflect new purpose.
Please review again! :)

**Review by VladimirSlavik — APPROVED** [review]
Thank you, looks good to me now.

**Review by rvykydal — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
